- tasks/prime.py
CreateMoveTaskOrder task added to load testing. 
The load test should run when you run 
`locust -f locustfiles/prime.py `
And you should see a second line in the locust UI for this endpoint. 
POST  | /support/v1/move-task-orders
-- | --
In the logger you should the output of the createMoveTaskOrder test
```
[2020-06-23 10:04:14,133] ../INFO/tasks.prime: ℹ️ Create MTOs status code: 201
[2020-06-23 10:04:14,133] ../INFO/tasks.prime: ℹ️ MoveTaskOrder 9b6a8586-53ad-4349-94c4-2025365adf7a created!
```
You can setup using the directions in https://github.com/transcom/milmove_load_testing
> [MB-2971] CreateMoveTaskOrder task added

- tasks/prime.py
* In order to build the Prime API task sequence, we need to make every newly created MTO available to prime. 
* This PR adds that functionality to the existing createMoveTaskOrder task in the Support task set.
Sandy and I discussed keeping it in the createMoveTaskOrder function since this is specific to the Prime API and we need every MTO to be available to Prime. Let me know if you have any other thoughts on structure!
```sh
locust -f locustfiles/prime.py
```
* Open http://localhost:8089/
* Enter values for users, hatch rate, and `local` for host
* Run and observe. You should see plenty of PATCH requests to `/available-to-prime`.
* [Jira story](https://dp3.atlassian.net/browse/MB-3080) for this change.
> MB-3080 Makes newly created mto available to prime

- requirements.txt
- tasks/prime.py
This PR adds `createMTOServiceItem` handler to the `PrimeTasksSet` for load testing integration. 
See inline comments. 
1. Start and run `mymove` Prime API
```sh
mylaptop ~ %: cd /mymove
mylaptop ~ %: make server_run
```
2. Load end to end data depended for load test. 
```sh
mylaptop mymove  %: make db_dev_e2e_populate
```
3. Start Locust load testing framework and run `createMTOServiceItem` test. 
```sh
mylaptop ~ %: cd /milmove_load_testing
mylaptop milmove_load_testing  %: locust -f locustfiles/prime.py --host local -T createMTOServiceItem 
```
4. After starting load tests, ensure handler responds with `200` status code 
* [Jira story](https://dp3.atlassian.net/browse/MB-2712) for this change.
> Adds task to PrimeTasksSet for CreateMTOServiceItem 

- tasks/prime.py
Adds tasks to prime load tests to create payment request
- using static data created by `make db_dev_e2e_populate` til the card where we have a sequence of tasks is started
`milmove`
make db_dev_e2e_populate
`milmove_load_testing`
10 users to simulate
10 hatch rate
POST /payment-requests should have successful requests made
* [Jira story](https://dp3.atlassian.net/browse/MB-2713) for this change.
> MB-2713 Create Payment Request Task

- tasks/prime.py
- utils/constants.py
This PR adds `createUpload` handler to the `PrimeTasksSet` for load testing integration. 
See inline comments. 
1. Start and run `mymove` Prime API
```sh
mylaptop ~ %: cd /mymove
mylaptop ~ %: make server_run
```
2. Load end to end data depended for load test. 
```sh
mylaptop mymove  %: make db_dev_e2e_populate
```
3. Start Locust load testing framework and run `createUpload` test. 
```sh
mylaptop ~ %: cd /milmove_load_testing
mylaptop milmove_load_testing  %: locust -f locustfiles/prime.py --host local -T createUpload 
```
4. After starting load tests, ensure handler responds with `200` status code 
* [Jira story](https://dp3.atlassian.net/browse/MB-2712) for this change.
> MB-2712 Adds Locust Task for Create upload

- Makefile
- locustfiles/milmove.py
- tasks/__init__.py
- tasks/milmove.py
Adds a load test for the MilMove app that mimics the Office test, and hits the get logged in user endpoint.
I changed the user type for the office from "office" to "PPM office" based off of these values for User Type - https://github.com/transcom/mymove/blob/master/cypress/support/constants.js#L15. I'm not sure if this is the right thing to do, but I *believe* office task is no longer returning user unauthorized for the get logged in user endpoint.
Note: since it's the EOD for me and I'm OOO until next Tuesday, I forced my local commit to bypass pre-commit hooks, since they were failing for a couple of checks due to what I believe was my setup and installation with python 2 vs. 3, and then issues with nodenv and npm erroring on running pre-commit. The circle tests passed, so I believe …
> MB-3309 - Adds locustfile for MilMove app

- static/fake_data.json
- utils/fake_data.py
* This PR replaces Faker's generated data for first name, last name, and street address, with MilMove's approved safe fake data.
* Data from spreadsheet is stored in `static/fake_data.json`
* The createMoveTaskOrder endpoint isn't dynamically creating data yet, so you won't be able to use it to verify
* Use GET /move-task-orders and review the newly added mto_shipments to see the fake data
* Addresses -> street_address_1, etc.
* Names -> Agents
```sh
make dev_db_e2e_populate
```
* [Jira story](https://dp3.atlassian.net/browse/MB-2970) for this change.
> MB-2970 Connect name and address fields to approved data json

- README.md
- utils/fields.py
This PR updates the README with detailed instructions/examples for how to use the `APIParser` class to generate fake data for a request. It also adds a little function to the `ObjectField` class because it made sense to have one after thinking more about use-cases for examples.
Read the instructions under [Fake Data Generation](https://github.com/transcom/milmove_load_testing/tree/sw-mb-2968-update-readme#fake-data-generation) and run the Prime load tests to check that my code updates didn't break testing.
In the `mymove` directory:
```sh
make db_dev_e2e_populate
```
In the `milmove_load_testing` directory:
```sh
make rebuild
```
Pay special attention to the `/mto-service-items` endpoint as the change would cause this one to fail if it was set up …
> MB-2968 Update README with APIParser instructions

- locustfiles/prime.py
- tasks/prime.py
This PR adds a task to hit the `updateMTOShipment` endpoint to the `PrimeTasks` task set. It uses a rudimentary process to pass shipment IDs and eTags from the `create_mto_shipment` task to this one, and populates most of the payload with fake generated data. Some overrides are implemented because those fields require more complexity and need the architecture from [MB-3244](https://dp3.atlassian.net/browse/MB-3244) to be successful.
**KEEP IN MIND:** The Support API task `create_move_task_order` is currently broken due to changes from the consolidation of the MilMove database. There is a ticket in the backlog to fix this, and it won't be addressed in this ticket.
Run the server in `mymove`:
```sh
make db_dev_e2e_populate && make server_run
```
Then in `milmove_load_testing`, rebuild the …
> MB-2714 Add update_mto_shipment task

- README.md
- tasks/base.py
- tasks/prime.py
- utils/constants.py
- utils/fake_data.py
- utils/fields.py
- utils/parsers.py
This PR changes the hardcoded payload for the task `create_move_task_order` so that it functions with the changes after consolidating the DB. It also reworks the way overrides work so that it's a little more intuitive. There's also some general clean up and fixing of other issues (such as the `create_mto_shipment` task). 
You will need to checkout the `sw-mb-3398-fix-create-mto` branch in the `mymove` repo in order to test these changes. Here is the PR: https://github.com/transcom/mymove/pull/4515
To run this against the changes to the YAML for the support and prime APIs, you may need to change the hardcoded url in `PrimeAPIParser` and `SupportAPIParser` to use the correct branch as well (instead of master). You can reasonably test without doing this however, and it will let you see that …
> MB-3398 Support API: Fix load testing task for createMoveTaskOrder endpoint

- tasks/prime.py
This PR updates the fake payload for the `create_move_task_order` Support task to use a new static ID for the required `uploadedOrdersID` field. This change depends on [this PR](https://github.com/transcom/mymove/pull/4563) in the mymove repo to be merged.
Checkout the `sw-add-static-uuid-to-test-doc` branch in the mymove project and run the server:
```sh
make db_dev_e2e_populate && make server_run
```
Then test load testing with `make load_test_prime` and verify that all endpoints have mostly 2xx response codes, and in particular make sure that the `POST | /support/v1/move-task-orders` request is mostly successful.
* Required PR: https://github.com/transcom/mymove/pull/4563
> MB-3398 Add new uploadedOrdersID that's actually static

- tasks/prime.py
The ticket ([MB-3687](https://dp3.atlassian.net/browse/MB-3687)) to change the `CreateMTOServiceItem` endpoint to return an array of service items caused an issue with the way the task in load testing was handling that endpoint. This PR fixes that up.
The `CreatePaymentRequest` endpoint sends back a lot of 500 errors - this is because basically every error returned from that endpoint is a 500 (as opposed to 409, 412, etc). There is some discovery that needs to happen to smooth out the responses there.
First set up and run your MilMove server (in the `mymove` directory)
```sh
make db_dev_e2e_populate && make server_run
```
Start up load testing for the Prime API (and run `make rebuild` if you might have out of date requirements):
```sh
```
Open http://localhost:8089 …
> MB-3687 Add handling for array of service items in prime data

- tasks/prime.py
* Adds task to `supportTasks` for updateMTOShipmentStatus.
* Includes additional `status: submitted` in creating MTOs to work around an issue with the state of a move when creating mtoServiceItems.
```sh
```
* [Jira story](https://dp3.atlassian.net/browse/MB-3290) for this change.
> MB-3290 Add updateMTOShipmentStatus task

- tasks/prime.py
This PR adds `updateMTOServiceItemStatus` handler to the `SupportTasksSet` for load testing integration. 
See inline comments. 
1. Start and run `mymove` Prime API.
```sh
mylaptop ~ %: cd /mymove
mylaptop ~ %: make server_run
```
2. Load end to end data depended for load test. 
```sh
mylaptop mymove  %: make db_dev_e2e_populate
```
3. Start Locust load testing framework and run `updateMTOServiceItemStatus` test. 
```sh
mylaptop ~ %: cd /milmove_load_testing
mylaptop milmove_load_testing  %: locust -f locustfiles/prime.py --host local --headless -u 5 -r 5
```
4. After starting load tests, ensure handler responds with `200` status code, specifically for `PATCH /prime/v1/mto-shipments/:mtoShipmentID/status`.
* [Jira story](https://dp3.atlassian.net/browse/MB-3289) for this change.
> [MB-3289] Adds task for updateMTOServiceItemStatus handler.

- tasks/base.py
- tasks/prime.py
This ticket was to add a task for the endpoint updateMTOServiceItem. This endpoint needs DDDSIT or DOPSIT items to update. Those items are created when you create a DOFSIT or DDFSIT item as those create a trio of SIT items. 
So this code adds tasks to request DOFSIT or DDFSIT creation, and to also request updating the DDDSIT or DOPSIT items. 
Some fixes that went in this code
- missing agents check
- log url and method when we have an error response
- make createMTOServiceItems accept and apply overrides
- update response strings to use the operationID for consistency
You need a lot of requests for there to be enough to create the specific types you want. 
- run Locust with make load_test_prime
- In the locust load test, select 50/10 for number of "users to simulate" and for "swarm rate". …
> MB-5820 Load testing UpdateMTOServiceItem

- Dockerfile
- Makefile
- README.md
- __init__.py
- docker-compose.local.yaml
- local_locust.py
- tasks/prime.py
This PR's purpose is to add a Docker container that can run load testing and talk to our local mymove server. 
It also adds several small quality-of-life fixes throughout the code. Most prominently, it adds _back_ the `update_mto_shipment_address` task, which seems to have been deleted in a bad merge. 
* First, make sure your local mymove server is running. To continue, you must also have `docker` and `docker-compose` installed on your system.
* Build the Docker container using either the Makefile command:
```sh
make local_docker_build
```
Or the docker-compose command:
```sh
docker-compose -f docker-compose.local.yaml build
```
* Once that process has completed, run the docker container using one of:
```sh
make local_docker_up
```
```sh
docker-compose -f docker-compose.local.yaml up
``` …
> MB-5757 Add a Docker container to run load testing locally

- tasks/__init__.py
Sets InsecureRequestWarning to trigger only once vs each time. 
Definitely upto you if you think we should do this. 
Con - easier to miss the warning since it's triggered only once
Pro - if we don't do it, easier to miss actual errors in the log due to the flood of warnings.
Run any load testing, check for warning to appear once. 
```
/Users/shimona/.pyenv/versions/3.8.3/envs/locust-venv/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: 
InsecureRequestWarning: Unverified HTTPS request is being made to host 'primelocal'. Adding certificate verification is 
strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
```
> Makes InsecureRequestWarning trigger only once

- tasks/base.py
- tasks/prime.py
Added a task for `updatePaymentRequestStatus` to load testing, checked that there were some successful runs. 
Please run load testing with 
```sh
```
You need a lot of requests for there to be enough to create the specific types you want.
- run Locust with make load_test_prime
- In the locust load test, select 50/10 for number of "users to simulate" and for "swarm rate".
- Check to see how many failures there are.
Then watch the Locust statistics page and wait for at least a few hits on the /support/v1/payment-requests/{paymentRequestID}/status patch command.
Then check your logs and see if you can find some successful updatePaymentRequestStatus calls. 
```
tasks.base: ℹ️ updatePaymentRequestStatus status code: 200
tasks.base: ℹ️ updatePaymentRequestStatus …
```
> MB-3240 Added updatePaymentRequestStatus task to load testing

- tasks/prime.py
- utils/constants.py
Create new endpoint for updateMTOPostCounselingInformation
Please take a look at the overall code, and make sure the response was created correctly.
To get locust running and see the new endpoint:
```python
```
In locust set the # of total users and the spawn rate to 5
* [Jira story](https://dp3.atlassian.net/browse/MB-2715) for this change.
> MB-2715 -Update-post-counseling-information

- tasks/prime.py
This PR is needed due to changes to the Support API endpoint updateMTOServiceItemStatus in: 
https://github.com/transcom/mymove/pull/5595
- run Locust with make load_test_prime
- In the locust load test, select 50/10 for number of "users to simulate" and for "swarm rate".
- Check to see how many failures there are.
Then watch the Locust statistics page and wait for at least a few hits on the ` PATCH    /support/v1/mto-service-items/{mtoServiceItemID}/status` command. 
Then check your logs and see if you can find some successful updateMTOServiceItemStatus calls. Note there is a different endpoint called updateMTOServiceItem. 
Since the logs are hard to read, here are some things to check for
[MB-6113 Support API updateMTOServiceItemStatus returns a malformed service …
> MB-6113 Load Testing: Fix endpoint task for updateMTOServiceItemStatus

- README.md
- docker-compose.yaml
- locustfiles/prime.py
- requirements-dev.txt
- tasks/base.py
- tasks/prime.py
- tasks/tests/test_prime.py
- tasks/tests/test_prime_workflow.py
- utils/hosts.py
- utils/parsers.py
This PR removes the hardcoded IDs for:
- `contractorID`
- `uploadedOrdersID`
- `destinationDutyStationID`
- `originDutyStationID`
All of these values are required for the Support API endpoint `createMoveTaskOrder`, which is the pivotal request in our load testing process because it gives us MTOs to work with. In order to run these tests in experimental, we must grab these values from MTOs that already exist in the experimental database. We use the Support API `getMoveTaskOrder` endpoint to do this with the moves we get back from the Prime API's `fetchMTOUpdates`.
To test this update, you must work with the `mymove` updates in this PR: https://github.com/transcom/mymove/pull/5861. For a local test, checkout and run the server off the branch `sw-upd-create-mto-for-load-testing`. For a test …
> MB-6656 Dynamically retrieve required move IDs to create MTOs in Experimental

- tasks/base.py
- tasks/prime.py
- tasks/prime_workflow.py
This ticket adds more calls to the prime workflow. These are in the `prime_workflow.py` file.
Added workflow chunks for 
* Add shipment with doshut service and approve
* update shipment agent and address
To support that, did a bunch of cleanup and update on the tasks in `tasks/prime.py`
* Reduced logger printouts on successful calls
* Updated tasks to request a specific object from storage if called with overrides.
* Updated tasks to return the new object on successful call to the endpoint
* Documented all overrides in tasks
**This branch depends on the same named branch in the mymove repo**
Here is that PR : https://github.com/transcom/mymove/pull/5905
- run Locust with make `load_test_prime_workflow`
- In the locust load test, select 25/10 for number of "users to simulate" and for …
> [MB-6219] Add shipments and serviceitems to the prime workflow in load testing

- tasks/prime.py
- tasks/prime_workflow.py
- utils/fake_data.py
- utils/tests/test_fake_data.py
This PR adds two steps in the prime workflow: create payment request and create upload.
This also adds a fake data function to return a valid post code in the lower 48.
@shimonacarvalho created an accompanying PR to fix somethings in mymove. When testing this PR, please run the server against this PR: https://github.com/transcom/mymove/pull/5939 
* Start the server locally `make server_run`
* in the milmove_load_testing repo, run ` make load_test_prime_workflow`
When to webpage pops up, enter 25 and 10.
* [Jira story](https://dp3.atlassian.net/browse/MB-6220) for this change.
> MB-6220 Add steps in prime workflow

- utils/fields.py
- utils/tests/test_fields.py
- utils/tests/test_parsers.py
This PR adds unit tests for all of the methods in the ObjectField class. It also fixes some bugs encountered along the way.
To run only the new tests:
```sh
pytest -v -k TestObjectField utils/tests/test_fields.py
```
And to run all tests:
```sh
pytest
```
* [Jira story](https://dp3.atlassian.net/browse/MB-5958) for this change.
> MB-5958 Add unit tests for utils.fields.ObjectField

- tasks/prime.py
- utils/fake_data.py
- utils/tests/test_fake_data.py
Previously, load testing would generate random UUID's for tests. This led to foreign key errors being through when calling `updateMTOServiceItem` and `createMTOServiceItem`. To fix this, the faker now returns an empty uuid. The empty uuid is ignored by swagger/handlers and they won't be updated now. 
To test that this works, run load testing and confirm that no 500 errors appear for 
`PATCH | /prime/v1/mto-service-items/{mtoServiceItemID}` and `POST | /prime/v1/mto-service-items`.
To run load testing run `make db_dev_e2e_populate` and `make server_run` in the mymove repo. Then run `make load_test_prime` in the load testing repo.
* [MB-6698](https://dp3.atlassian.net/browse/MB-6698) for this change.
* [MB-6697](https://dp3.atlassian.net/browse/MB-6697) for this change.
> MB-6698 Fix updateMTOServiceItem 500 errors during load testing

- utils/parsers.py
- utils/tests/test_parsers.py
For the Domestic Crating MTO Service Items, the API parser has to generate a set of dimensions for the item and a set of dimensions for the crate that item is going to be put in. These values are all random integers, but we have to make sure the item is smaller than the crate for the endpoint to work.
With the old code, we would just set the item value to be the same as the crate's - 1 so that we knew it was smaller:
```python
if item <= crate:
item = crate - 1
```
However, in rare cases, the generator would pick 0 as a value for one of the crate's dimensions! In that case the item, would get -1! We don't want to break the rules of space and time with this code, so I've changed the above code to also make sure both values are above 0.
To test this in action, run load testing for a while …
> MB-7225 Stop generating negative crate dimensions

- .pre-commit-config.yaml
- tasks/prime.py
- tasks/prime_workflow.py
- tasks/tests/test_prime.py
- utils/parsers.py
PR to align with the updates in MilMove to change the "MoveOrder" object to be called "Order." Chore for this work: https://dp3.atlassian.net/browse/MB-7103
Review after https://github.com/transcom/mymove/pull/6120 is merged.
In the `mymove` directory:
```sh
```
Then in `milmove_load_testing`:
```sh
```
Select ~10 users at whatever spawn rate you wish. Verify that most responses are successful, particularly for the support task to create MTOs. (Other tasks, like the MTO Service Items and some support status endpoints have known issues. Their failures are not blockers.)
> MB-7103 Rename moveOrder to order

- tasks/prime.py
This PR adds an override for a valid TAC to the request payload for `create_move_task_order`. Note that it also depends on the changes in https://github.com/transcom/mymove/pull/6288 to fully fix the issue (there were other validation errors in the backend).
Wait for https://github.com/transcom/mymove/pull/6288 to be merged, or modify line 447 in `utils/parsers.py` (the `SupportAPIParser`) to point at branch `sw-mb-7400-add-fields-to-create-mto` instead of `master`. You'll also need to checkout this branch in your mymove repo.
Run your `mymove` server:
```sh
make db_dev_e2e_populate server_run
```
Then, in `milmove_load_testing`, run the `prime_workflow` test:
```sh
make load_test_prime_workflow
```
Verify that every task succeeds.
* [Jira story](https://dp3.atlassian.net/browse/MB-7400) …
> MB-7400 Add a valid TAC override to create MTO

- tasks/prime.py
Changes the `update_mto_shipment` task to use PATCH - whoops!
In `mymove`:
```sh
make db_dev_e2e_populate server_test
```
In `milmove_load_testing`:
```sh
make load_test_prime_workflow
```
* [Jira story](https://dp3.atlassian.net/browse/MB-8020) for this change.
> MB-8020 change update shipment to patch

- locustfiles/office.py
- tasks/__init__.py
- tasks/office.py
- utils/constants.py
This PR expands the GHC API testing to incorporate distinct Services Counselor and TOO office users making requests to the [getMove endpoint](http://milmovelocal:3000/swagger-ui/ghc.html#/move/getMove).
I incorporated the same kind of local storage that the Prime uses as a mixin to both set of office user tasks.  I added tasks to request the queue data for each user type, which will populate the local storage with move data in different statuses.  There is overlap from the Services Counselor moves and TOO moves for those in the `SERVICE COUNSELING COMPLETED` status so what ends up in the local store will naively contain duplicates at this time.
To make things more realistic, I did work on randomizing creation of move data for the services counselor user because the seed only had 1 or 2 …
> [MB-7254] GHC API load testing getMove endpoint for SC and TOO

- Makefile
- README.md
MilMove devs are already using ASDF. This adds the the option to continue using ASDF instead of pyenv.
Command to get the Customer app running for load testing:
Startup milmove server:
```sh
```
Follow the README to setup you env. To use ASDF you can do the following:
Note: python 3.8.3 failed to install on my machine so I actually used latest which was 3.9.5. To bypass using 3.8.3 in the Makefile you can manually install python instead of letting the Makefile do it. Try out the Makefile first and if it fails then move on to do it manually and then run the Makefile again. 
```sh
brew install openssl readline sqlite3 xz zlib
asdf plugin add python
USE_ASDF=true make  venv
USE_ASDF=true make  setup
``` …
> Add option to use ASDF in makefile

- README.md
- locustfiles/prime_workflow.py
- tasks/__init__.py
- tasks/prime.py
- tasks/prime_endpoint_workflows.py
- tasks/prime_hhg_workflow.py
- tasks/prime_workflow.py
This PR adds a new file `prime_endpoint_workflows.py`. The intent of this file is to create workflows that will specifically target a single endpoint. To test the primeapi create_mto_shipment endpoint, run the following command:
`locust -f locustfiles/prime_workflow --tags createMTOShipmentWorkflow`
I also created added the first two pages to this repo's wiki 🎉 and updated the readme to point to the wiki for some custom test command information.
https://github.com/transcom/milmove_load_testing/wiki
The naming of the files is a little wonky. Do you have any better suggestions?
To load test the create_mto_shipment endpoint complete the following steps:
1. `make server_run` in the mymove repo
2. `locust -f locustfiles/prime_workflow --tags createMTOShipmentWorkflow` in the load testing repo …
> MB-7939 test create_mto_shipments endpoint

- tasks/prime.py
- tasks/prime_endpoint_workflows.py
- tasks/prime_hhg_workflow.py
Removes all references to `fetchMTOUpdates` and leverages the `listMoves` endpoint instead. Note that there are a number of _other_ issues with the Prime workflow at the moment that might be related to input. This PR doesn't address those.
To run the Prime workflow, first run your server in `mymove`:
```sh
```
Then, in `milmove_load_testing`, use the `prime_workflow.py` locust file:
```sh
make load_test_prime_workflow
```
> Use listMoves endpoint instead of fetchMTOUpdates

- .envrc
- nix/default.nix
- utils/hosts.py
DP3 hosts use well known Certificate Authorities so we don't need special CA bundle.
This works for me locally:
```
locust -f locustfiles/prime.py --host dp3
```
I found the keys for load testing in the dp3 1Password. I used `chamber write` to populate them so they should be set now
```sh
echo "Code goes here"
```
* [Jira story](tbd) for this change.
* [This article](tbd) explains more about the approach used.
> Add support for DP3 environment

- .envrc
- nix/default.nix
- utils/hosts.py
This PR includes Drew's PR to enable locust testing against the dp3/load test environment https://github.com/transcom/milmove_load_testing/pull/80
See Drew's PR for review notes and set up steps
```sh
locust -f locustfiles/prime.py --host dp3
```
* [Jira story](tbd) for this change.
* [This article](tbd) explains more about the approach used.
> MB-9667 PR for enabling load test against the dp3/load test environment

- Dockerfile
- README.md
- ecs/milmove_load_testing_ecs.json.tmpl
- scripts/codebuild
This PR adds support to the codebuild script to read the locustfile override env when triggering a new load test build.  We then inject that value to allow the user to run the prime, office, or customer load test scripts on the existing deployed container at port 4000.
The task definition change to support this has to be done in Terraform in another PR https://github.com/transcom/transcom-infrasec-gov-nonato/pull/84
I'll update this with the new task definition number when the infra PR gets merged and creates a new revision.
1. Login to the AWS console from the transcom-infrasec-gov repo with `make aws_console_transcom_gov_dev`
2. …
> [MB-9782] Update dockerfile and codebuild script to override locustfile command

- .circleci/config.yml
- .envrc
- .pre-commit-config.yaml
- .python-version
- Brewfile.local
- Dockerfile
- Makefile
- Pipfile
- Pipfile.lock
- README.md
- fresh-brew.local
- nix/default.nix
- pyproject.toml
- requirements-dev.txt
- requirements.txt
- tasks/prime.py
- tasks/tests/test_office.py
- tasks/tests/test_prime.py
- utils/base.py
- utils/constants.py
- utils/fake_data.py
- utils/fields.py
- utils/hosts.py
- utils/parsers.py
- utils/tests/test_fake_data.py
- utils/tests/test_fields.py
- utils/tests/test_hosts.py
- utils/tests/test_parsers.py
Pipenv lets us manage dependencies and creates a lock file so we can have reproducible builds.
In addition, `direnv` supports it natively and will install the dependencies and manage the virtualenv for us.
I also took the opportunity to get the pre-commit in sync with the dependencies and use a `pyproject.toml`
Finally, I fixed the tests and enabled them in CI
I've tested this out with nix and as much as I can with brew, although I don't use it extensively, so any validation you all can do would be great
Check out the code and try to follow the README to get your environment set up
> MB-10413: Convert to using pipenv to manage dependencies

- .circleci/config.yml
- Brewfile.local
- Makefile
- Pipfile
- Pipfile.lock
- nix/default.nix
While prepping for demo, I realized that my venv was using python 3.9.9. Apparently we need to explicitly set `python_full_version` in `Pipfile`. Otherwise defaults to system default, as long as it's 3.9.*. So for me, my venv was being created with python 3.9.9. I guess I must have updated my global python version since I last messed with this just last week haha.
This then led to an issue with the docker image we were using since it didn't have python 3.9.6 nor pyenv/asdf to install the right python version. Switched to using CircleCI's python docker image since it has what we need (even comes with `pipenv`) and [CircleCI built it specifically for running in CI](https://circleci.com/docs/2.0/circleci-images/#next-generation-convenience-images). 
The problem with the python image though, …
> MB-10413 Explicitly set python_full_version in `Pipfile`

- locustfiles/prime.py
- tasks/prime.py
- utils/constants.py
- utils/fake_data.py
- utils/hosts.py
- utils/parsers.py
This adds a starting point for initializing seed data within the `prime.py` locust test flow. For each user we are logging into dev-local and attempting to go through the entire customer flow. Right now these changes just create the user and adds all of the information needed to setup their profile.
Note: Some of this code should be refactored if it is being used in other tests. 
```sh
locust -f locustfiles/prime.py --host local
```
* [Jira story](https://dp3.atlassian.net/browse/MB-10536) for this change.
> MB-10536 Add starting point for customer seed data for prime

- tasks/base.py
- tasks/prime.py
This fixes tests for creating an MTO shipment when multiple agents have the same type. This also adds a tests for an intentional failure, for having multiple agents of the same type.
Do we want to maintain logging for expected failure cases? Using the `check_response` helper method causes the output in the terminal to be verbose. When we have an error check_response logs the entire json payload which in this case is ~45 lines.
```sh
```
* [Jira story](https://dp3.atlassian.net/browse/MB-10652) for this change.
> MB-10652 create shipment

- .github/dependabot.yml
This PR creates a dependabot config in `.github/dependabot.yml` to run daily at 11:00 (the same as mymove) for both the pipenv dependencies and the docker dependency.
I will need to update the [dependencies documentation](https://dp3.atlassian.net/wiki/spaces/MT/pages/1419870254/Dependency+Updates+Process+Working+Document) to make sure these are taken care of with the others.  Since GitHub acquired Dependabot I noticed some [broken links in the mymove-docs repo](https://transcom.github.io/mymove-docs/docs/tools/dependabot/manage-dependabot) too redirected to the wrong places.
Once merged we can manage dependabot from the insights -> dependency graph -> dependabot page https://github.com/transcom/milmove_load_testing/network/updates
[Dependabot configuration …
> [MB-10562] Create dependabot config for pipenv and docker

- tasks/prime.py
- tasks/tests/test_prime.py
Adds move setup as part of the prime load tests.
The code is a giant block of code at the moment and likely will be worthwhile to separate out where the comments are made for each distinct step. I have tentatively refrained from doing this because there are some potential changes with how/where this will be used in [Felipe's PR](https://github.com/transcom/milmove_load_testing/pull/97) and the unknowns of how and if these functions will be used by other tests. In addition to those reason, we are also utilizing some of the data from previous steps so this will require some level of data management / parameters to refactor.
When running the prime load tests using
```sh
```
you should be able to log into the the most recently created user to see that they have …
> Mb 10647 rp create moves

- tasks/prime.py
Changing the default origin duty location for moves created within the prime setup to belong in the `KKFA` GBLOC
Reset local DB (in mymove repo):
```
make db_dev_reset
make db_dev_migrate
```
Run local back-end server (in mymove repo):
```
make client_run
```
Run front-end server (in mymove repo):
```
```
Run the load test (in milmove_load_testing repo):
```
```
You can cancel this test as soon as you see the `/internal/moves/{moveId}/submit` test succeed. 
You should then log into the local office Service counselor to confirm that you can see the move that was created by the prime load test. (If you cleared your DB and only run the prime tests with one user you should only see one …
> Rp update duty location

- README.md
- tasks/prime.py
- utils/auth.py
This adds a section in the docs explaining how to handle expected failures.
Seconday things added:
* While adding this section, I noticed a few places in the README that I forgot to update (e.g. to use `HTTPStatus` or our new `log_response_info` and `log_response_failure` functions). 
* In writing the sample failure load test, I realized:
* we don't quite have that test so I added it to our real load tests.
* we had previously had a `list_moves` load test that existed to set the default mto IDs, but we got rid of it when we started creating the move in the `PrimeTasks.on_start` method. I agree we don't need it for that, but realized that we probably should still have load tests for the endpoint itself.
Did I miss something? Or should something be explained more?
If you want to run the new …
> MB-10534 Add docs for expected failures

- utils/fake_data.py
- utils/tests/test_fake_data.py
The test I wrote for the safe middle name generation is flaky because there are a lot of fake names we have without middle names. When I wrote the test and ran it, I guess I just got lucky and didn't have any of my runs select two people without middle names. This fixes it so that the check that compares them only runs if at least one of them is not empty.
```sh
pytest
```
* [Jira story](https://dp3.atlassian.net/browse/MB-10593) for this change.
> MB-10593 Fix flaky fake middle name test

- .envrc
- nix/default.nix
- nix/update.sh
Updated `NIX_PROFILE` path for multi-user installs. 
Since I don't have an M1 mac, I wasn't sure which packages needed to be updated for that so I just got newer hashes for all the packages that had one, keeping the same version as before.
Can someone with an M1 mac that uses nix check that this works?
1. Follow [`nix` setup instructions](https://github.com/transcom/milmove_load_testing#setup-nix)
> MB-11016 Update nix setup

- .pre-commit-config.yaml
Upgrade to a version of trussworks/pre-commit-hooks that supports hadolint on M1 Macs 
See https://github.com/trussworks/pre-commit-hooks/releases/tag/v1.1.1
Having someone with an M1 and a non-M1 mac try would be helpful.
Make sure the following works
```sh
pre-commit run hadolint --verbose --all-files
```
Sample output
```sh
Run hadolint Dockerfile linter...........................................Passed
- hook id: hadolint
- duration: 0.3s
```
* [This slack thread](https://trussworks.slack.com/archives/C02KTA0RS57/p1643762508474119) for this change.
* [This slack thread](https://ustcdp3.slack.com/archives/CP6PTUPQF/p1639414590066100) explains more about the approach used.
> Upgrade to hook for hadolint that works with M1 MacBook

- tasks/milmove.py
- tasks/office.py
- tasks/prime.py
- tasks/tests/test_prime.py
- utils/parsers.py
I renamed all instances of the term `duty station` in load testing code to `duty location`. This terminology change has already been done in the API and application code, so some load tests were failing when they tried to reference non-existent duty station keys in payloads.
Most of these places weren't generating noticeable errors, but I think that's because they were on code paths that were hitting earlier exceptions first. I haven't rigorously tested this hypothesis, but I'm confident that these keys are not used in any of our responses anymore and needed to be updated.
Run some load tests and make sure you don't see any exceptions that mention duty stations or duty locations
```sh
make load_test_office
make load_test_milmove
```
for example, this exception that …
> Rename duty station to location

- tasks/queue.py
- utils/flows/simple_hhg.py
- utils/flows/steps/milmove.py
This pull request (a rewrite of #155 ) adds additional methods and weighted randomness into the `MilMoveHHGQueueTasks` task set, which call different implementations of the existing simple HHG flow. Those implementations differ by passing into a common function (which does the customer part of a move) a list of shipment types - one HHG, two HHGs, or an NTS - and sending different payloads to the server based on those different shipments.
Start locust with a command like
```
locust -f locustfiles/queue.py --host local -u 10
```
Open http://localhost:8089/ and ensure that the user weights for MilMoveHHGUser are >= 1, then start the load tests and validate that no failures are returned or exceptions are thrown.
> MB-11921: Adds weighted randomness to flow shipment types, and NTS shipments

- README.md
- pyproject.toml
Pytest commands as mentioned in docs don't actually work as-is. 
Fixed.
> Fix pytest commands in documentation

- .pre-commit-config.yaml
This PR updates and/or syncs pre-commit hook versions since it looks like it's been a while since we've updated them (and dependabot doesn't catch pre-commit hooks).
~~Note that I held flake8 back to 5.0.4 instead of the very recently released 6.0.0 version to match what's in our Pipfile (ideally, we'd update both in sync, but the dependabot update for the Pipfile hasn't come through yet).~~  **Update:** it looks like the [dependabot PR for flake 6.0.0](https://github.com/transcom/milmove_load_testing/pull/291) is available now, so I went ahead and updated the pre-commit hook to 6.0 too in this PR.  Both PRs should be landed close together.
Just make sure pre-commit hooks pass in CircleCI.
You can also run a `pre-commit autoupdate` and see if any other updates (besides the flake8 one …
> [MB-14473] Update/sync pre-commit hook versions

- utils/auth.py
- utils/tests/test_auth.py
[Modify load testing to not hammer db using devlocal auth.
](https://dp3.atlassian.net/browse/MB-16132)
Hitting `/devlocal-auth/login` does a pretty suboptimal query that is nothing like what would happen in production.
```sh
echo "Code goes here"
```
* [Jira story](tbd) for this change.
* [This article](tbd) explains more about the approach used.
> MB-16132: Don't hammer the DB for devlocal auth

- utils/auth.py
- utils/flows/__init__.py
- utils/flows/steps/milmove.py
- utils/openapi_client.py
- utils/tests/test_auth.py
Use locust to track the status of devlocal auth interactions. Stop processing the flow if an error occurs
This is an attempt to have locust stats for errors match the errors in the server logs
> MB-16145 better track locust failures, stop flow if error occurs

- .envrc
- README.md
- nix/default.nix
- nix/update.sh
After more experimentation and testing, I confirmed that pipenv can create python enviornments for the installed version of python which is different from the version of python used to install pipenv itself.
> Go back to installing pipenv via nix

- utils/flows/steps/milmove.py
[Ticket B-18519](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A894599)
Had to dive into hosting locust locally and testing against a locally running milmove db. From this, I was able to debug the milmove handler and find missing / incorrect parameters. Then, just updating the locust test file accordingly.
Please see "This pull request" section to see why the failure was not identified. Going forward, if we automate this, then we'll need to update the pipeline into main to check for any failing locust tests based on changes.
Since we removed rank from the service member and tied everything to now be based on the order pay grade, load tests were still using "ServiceMemberRank" which no longer existed in swagger. A previous pull request removed this.
We had to …
> updated create order parameters for locust tests

- utils/flows/steps/milmove.py
Work done as part of [B-18798](https://github.com/transcom/mymove/pull/12348/files#diff-c746751dbab37ada7a220eadb1e197830634fc397ecf9efed38d5dfaeebcfa94) and upcoming work as part of [B-18799](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=B-18799) will require valid zip codes in milmove_load_testing so that county lookups can be completed. 
The use of fake.postcode() was generating random zip codes that are invalid, which would cause the county lookup to fail when trying to patch the service member.
> Stop generating random postal codes so that county lookup works
