transcom/milmove_load_testing

.circleci/config.yml, .pre-commit-config.yaml, Makefile
I'm doing similar work to this in another python repo and thought having it all updated would help.
=> Update circleci config, pre-commit hooks, and makefile for pre-commit tools

README.md
Fleshed out the README with some more instructions for how to contribute to the codebase. Wanted to make sure that there were enough code examples for someone totally new to the system to get started.
I guess give it a read and see if it seems clear and helpful!
* [Jira story](https://dp3.atlassian.net/browse/MB-2966) for this change.
=> MB-2966 Update README

tasks/prime.py
Add CreateMTOShipment endpoint to load tests
`make load_test_prime`
Start swarm and see calls to POST /mto_shipments succeed
* [Jira story](https://dp3.atlassian.net/browse/MB-2709) for this change.
=> MB-2709 Create MTOShipment task

.flake8, .gitignore, README.md, locustfiles/prime.py, requirements.txt, tasks/base.py, tasks/prime.py, utils/base.py, utils/constants.py, utils/fake_data.py, utils/fields.py, utils/parsers.py
This PR adds a tool to parse the API files for the Prime and Support APIs using Prance that figures out which data type we want for each field, and then it connects with Faker to generate fake data for the type we selected. It has been implemented with the Prime API tasks `create_mto_shipment` and `create_mto_service_item`.
A good order to view these changes in so that you can see the flow of the code would be:
`utils/fake_data.py` > `utils/fields.py` > `utils/parsers.py` > `locustfiles/prime.py` > `tasks/base.py` > `tasks/prime.py`
All the other changes are fairly small and can be mixed in whenever it seems appropriate. 
The Support API still has some issues with its configuration -- mostly inconsistent formatting such as using snake-case for keys when we need to be using camel case. …
=> MB-2968 Create tool to generate fake data

.pre-commit-config.yaml, Makefile, README.md, tasks/prime.py
This PR adds more comprehensive instructions about the requirements and setup steps for this project to the README. It also adds a helpful `make rebuild` command for recreating the virtual environment.
Read and follow the instructions in the [Getting Started](https://github.com/transcom/milmove_load_testing/blob/sw-mb-3078-update-makefile/README.md#getting-started) section of the README.md, focusing on the [Requirements](https://github.com/transcom/milmove_load_testing/blob/sw-mb-3078-update-makefile/README.md#requirements) subsection in particular.
* [Jira story](https://dp3.atlassian.net/browse/MB-3078) for this change.
=> MB-3078 Update setup requirements and Makefile

README.md
Adds documentation to readme to include make command for milmove load testing
* [Jira story](https://dp3.atlassian.net/browse/MB-3309) for this change- an addendum to this story that is already merged.
=> Add documentation in readme about make command for milmove customer

.gitignore, Makefile, README.md
This PR adds `pyenv` as a requirement for the project. The Makefile has been modified to expect `pyenv` in an effort to make setup smoother, and the README has been updated with detailed instructions to walk you through the steps of installing `pyenv` and running the rest of the setup commands.
Please read the "Getting Started" section of the README and follow its instructions to set up the project with `pyenv`.
=> Add pyenv as a project requirement

tasks/prime.py, utils/constants.py
Add an endpoint to update the mto agent.
1. run Locust with `make load_test_prime`
2. In the locust load test, select 5 for number of "users to simulate" and for "swarm rate".
3. Check to see how many failures there are.
* [Jira story](https://dp3.atlassian.net/browse/MB-5819) for this change.
=> MB-5819-update-mto-agent

tasks/prime.py
One-character change so our `mtoServiceItem` data will log out with the error message.
=> Adds `f` so error message will print mtoServiceItem data

utils/fake_data.py, utils/tests/test_fake_data.py
This PR adds units tests for the MilMoveProvider and MilMoveData classes and their functions. 
My python is rusty, are there better ways to test? 
Execute `pytest utils/tests/test_fake_data.py`
* [Jira story](https://dp3.atlassian.net/browse/MB-5938) for this change.
=> MB-5938 unit test blitz

utils/tests/test_fields.py
This PR adds unit tests for the BaseAPIField, EnumField and ArrayField classes.
Execute `pytest utils/tests/test_fields.py` to run the tests
* [Jira story](https://dp3.atlassian.net/browse/MB-5937) for this change.
=> MB-5937 add unit tests for field.py

tasks/office.py, tasks/tests/test_office.py, utils/constants.py, utils/fake_data.py, utils/fields.py, utils/parsers.py
This PR adds the first patch requests to update orders, allowances, and customer/service member records as a SC or TOO would on their respective Move Details page.
I added my first pytests for the OfficeDataStorageMixin that caught a bug with how I was storing some things.  I also added more local storage for duty station IDs because faker will not generate valid ones for us.
I had to add custom faker logic for the TAC field that has to be 4 characters long.  I also extended the parser to read the minimum and maximum definitions for fields like proGear weight and then call the faker random_int function with those range limits.
Here is the [corresponding PR in the mymove repo](https://github.com/transcom/mymove/pull/6696) that makes some changes to the ghc swagger to required backupContact …
=> [MB-8071] Load test SC and TOO edit move details ghc requests

nix/default.nix, scripts/codebuild
Use the AWS CLI + jq to get the latest task definition so the deployment knows which one to update
=> Update the code build deployment to auto update the latest task definition

Makefile
This is a PR to update the makefile so that the make commands run without error.
Please verify the following commands work without an error:
```sh
make load_test_office
make load_test_milmove
make load_test_prime_workflow
```
* [Jira story](https://dp3.atlassian.net/browse/MB-10513) for this change.
=> MB-10513 cleanup makefile

.circleci/config.yml, .pre-commit-config.yaml, Brewfile.local, Dockerfile, locustfiles/all.py, nix/default.nix, scripts/aws-session-port-forward.py, scripts/codebuild
* Push a unique image tag per build based on the git sha
* Create a new task definition for every deploy with that image tag
* Override the LOCUSTFILE as necessary
I tested this out with a build override of this branch and it worked well
I based this on the [pipenv work](#84) since the Dockerfile needed to be updated. That means it's really only the last commit that's relevant
=> MB-10438: Update task definition on every build

Pipfile.lock
Just happened to notice some packages had updates and since we don't have a process in place, I figure a quick update was good.
I was just going to let CI run the tests, especially since some load tests are failing as is. If you'd like to run the repo tests locally, you can run
```sh
pipenv sync -d
```
then
```sh
pytest
```
=> Update python dependency versions

Pipfile, Pipfile.lock, utils/constants.py, utils/fake_data.py, utils/fields.py, utils/tests/test_fake_data.py, utils/tests/test_fields.py
When running load testing a lot of errors in the logs were failures because of an address that was not able to be geocoded by the HERE maps API service.  Part of that issue is that the faker library that we use chooses a random 5 digit number between a start and end range of state ZIP codes.  This is inaccurate because ZIP codes are not contiguously valid and we ended up using ZIP codes that don't exist.
Milmove uses a static source of ZIP codes that originates for the GeoNames database for some form address validation.  Instead of porting that to be python formatted and write helper lookups, I found a library https://github.com/seanpianka/Zipcodes that seems comprehensive and would give us supplementary data such as the city.
I added some handling to the object fields so now address …
=> [MB-10649] Prime update shipment avoid geocode failures by using non-faker zipcode library

tasks/queue.py, utils/flows/simple_hhg.py, utils/flows/steps/milmove.py, utils/flows/steps/prime.py, utils/flows/steps/service_counselor.py, utils/flows/steps/too.py
I added a flow that creates an HHG with a single shipment and creates two payment requests that cover all of its service items.
This is the first load testing scenario that goes through the flow up to creating a payment request, so I ran into some rough edges.
Specifically, there were a few places where return values from our API endpoints didn't match up with what the swagger spec said we'd get. I fixed some of these in [another PR](https://github.com/transcom/mymove/pull/8459), and opted out of return type checking in some other cases.
I also fixed a bug that appeared in multiple places around fetching the move from a queue.
The existing logic requested the first 100 things in the queue and checked if any of them matched the given move ID.
This doesn't really work when you get a large …
=> [MB-12077] add multiple payment request scenario

.pre-commit-config.yaml, Pipfile.lock, pyproject.toml, utils/flows/__init__.py, utils/flows/simple_hhg.py
Since we are using type hints, use pyright to ensure typing info is correct as part of pre-commit
Minor tweak to accurately represent type info
=> Use pyright to ensure typing info is correct, update deps

openapi_client/ghc/docs/ApproveSITExtension.md, openapi_client/ghc/docs/OrderApi.md, openapi_client/ghc/docs/ShipmentApi.md, openapi_client/ghc/docs/SitExtensionApi.md, openapi_client/ghc/docs/UpdateAllowancePayload.md, openapi_client/ghc/ghc_client/model/approve_sit_extension.py, openapi_client/ghc/ghc_client/model/update_allowance_payload.py
Regenerate client for sit extension and allowance payload changes
I can run locally against https://github.com/transcom/mymove/commit/f7bd101835e3b2c0a53f9bbef45b5af7a8fc4fca successfully
=> MB-16030: Regenerate client for sit extension and allowance payload changes

README.md
When the python version changes in the load testing repo, we also need to update mymove to use that python version
=> Document updating mymove load_tester image for python updates

utils/flows/__init__.py, utils/openapi_client.py
Log if the flow step fails, ensure the pool size is set up correctly
=> MB-16145: Log if the flow step fails, ensure pool size is always set

utils/request.py
Add additional `LOCAL_PRIME_PORT` for overriding the prime port separately
=> Fix default port for prime when running locally, docstring fixes

scripts/ecs-deploy.py
CPU load is getting close to the max, so bump up to give us more room
```sh
echo "Code goes here"
```
* [Jira story](tbd) for this change.
* [This article](tbd) explains more about the approach used.
=> MB-16242: Current load tests are hitting 85% CPU, bump up to give us more room

Pipfile.lock
Reverts transcom/milmove_load_testing#429
=> Revert "Bump pre-commit from 3.3.2 to 3.3.3"
